require:
  - rubocop-rails
  - rubocop-rspec

Lint/MissingCopEnableDirective:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 15
